# Welcome to Jekyll and Thank you for using Renge as your theme.

# Renge is designed by Junchao (www.junchaowang.com) and inspired by amination
# “のんのんびより” and named by one of the Characters "Renge Miyauchi (宮内 れんげ Miyauchi Renge)".
# If you have any questions, you can reach me via https://github.com/billyfish152 by submitting
# an issue or via email billyfish152@gmail.com.

# Please install jekyll-paginate before build it.
# sudo gem install jekyll-paginate in linux or MacOS.
# gem install jekyll-paginate in Windows.

# Renge supports categories and tags, which are defined in each of your posts.
# Also, You can add or removed links in /_includes/sider.html .
# please change the below settings to your own.

# Site settings
title: Sophie The Lionhart
email: sophielionhart@gmail.com
description: >
  Sophie The Lionhart's personal blog. Here you'll find posts about projects, programming concepts, Japan and Japanese, Korea and Korean, as well as the occasional
  cooking article.
#baseurl: "http://localhost:3000" # the sub path of your site, e.g. /blog
#baseurl: "http://www.sophielionhart.com" # the sub path of your site, e.g. /blog
#url: "http://localhost:3000" # the base hostname & protocol for your
#url: "http://www.sophielionhart.com" # the base hostname & protocol for your
github_username:  samuraiseoul

# Build settings
markdown: kramdown
paginate: 5
gems: [jekyll-paginate]
paginate_path: "/page/:num"
include: [ '_assets', '.nojekyll']

# Github Pages stuff
lsi: false
safe: true
source: './_site'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

domain: samuraiseoul.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://samuraiseoul.github.io/  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /blog/_site/      # place folder name if the site is served in a subfolder